### ISSUE TITLE
readme に書くこと

### ISSUE THREAD

**Issue by ndxbn** [ndxbn/my_windows_builder#1]
## TODO List

* [x] chocolatey のインストール（PoserShellでやる）
* [x] chocolatey の設定（`choco feature enable -n allowEmptyChecksums`）
* [x] ~~`package.config` を [gist](https://gist.github.com/ndxbn/1efffeac3c93c7d134c4451cf6591f46)から移動してくる~~
* [x] self update 機能を持つものは、chocolatey を使わないので、その一覧を作る
